preload = ~/Изображения/walpapers/wall2.png
preload = ~/Изображения/walpapers/anime/driving.jpg

wallpaper = eDP-1, ~/Изображения/walpapers/wall2.png
#wallpaper = DP-1, ~/Изображения/walpapers/wall2.png
wallpaper = HDMI-A-1, ~/Изображения/walpapers/anime/driving.jpg

splash = false
