
$hypr_conf_path = ~/.config/hypr/

source = $hypr_conf_path/monitors.conf
source = $hypr_conf_path/autorun.conf
source = $hypr_conf_path/bindings.conf
source = $hypr_conf_path/style.conf
source = $hypr_conf_path/inputs.conf
source = $hypr_conf_path/envs.conf
source = $hypr_conf_path/windowrules.conf

