
windowrulev2 = suppressevent maximize, class:.* # You'll probably like this.

windowrulev2 = float, class:^(org\.telegram\.desktop\..*)$
windowrulev2 = size 25% 90%, class:^(org\.telegram\.desktop\..*)$
windowrulev2 = move 74% 5%, class:^(org\.telegram\.desktop\..*)$


windowrulev2 = float, class:^(Rofi)$
windowrulev2 = size 25% 90%, class:^(Rofi)$
windowrulev2 = move 74% 5%, class:^(Rofi)$
